name: elden_ring_quest_guide
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '2.16.2'

dependencies:
  cached_network_image: ^3.2.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.10
  font_awesome_flutter: ^10.1.0
  injector: ^2.0.0
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  lottie: ^1.3.0
  provider: ^6.0.2
  reflectable: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.10

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - lib/data/
